name: dart_winapi
description: Dart implementation of winapi using dart:ffi to call C++ apis.
version: 0.3.2
homepage: https://github.com/Hexer10/dart_winapi

environment:
  sdk: '>=2.6.0 <3.0.0'

dependencies:
  meta: ^1.1.8
  ffi: ^0.1.3